version: "3.3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: fabianolvs@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
